version: '3'
services:
  web: # django 컨테이너
    image: server
    container_name: web
    command: bash -c "gunicorn modelproject.wsgi:application -b 0.0.0.0:8000" # 서버 실행
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
    networks:
      - server

  nginx: # nginx 컨테이너
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./cert/certbot/conf:/etc/letsencrypt 
      - ./cert/certbot/www:/var/www/certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - server

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./cert/certbot/conf:/etc/letsencrypt 
      - ./cert/certbot/www:/var/www/certbot

networks:
  server: